### ISSUE TITLE
Reference Section

### ISSUE THREAD

**Issue by ignacioct** [argilla-io/argilla#48]
Including a Reference section. For now it can have links to Python API docs, and we can think of more elements to add. @dvsrepo told me that you were working on the API reference, @dcfidalgo , how is it going?

**Comment by dcfidalgo** [comment]
Thanks for the reminder, i just opened a a PR #51 where i included a first version of the API reference. I will open a new issue to discuss the content of the API reference. See #55

**Comment by dvsrepo** [comment]
Nice! I like the simplicity for now with just the main user-facing classes and functions.

As we will eventually have a REST API reference and a UI (or app) reference, I would rather call it something like `Python library API` or just without the API, but I am open to suggestions.

Also some minor comments:

 

- [x] This docstring still refers to hf dataset as output (https://docs.rubrix.ml/en/latest/references/api_reference.html#rubrix.load) #57
- [x] I don't know if we should clearly state that https://docs.rubrix.ml/en/latest/references/api_reference.html#rubrix.client.models.TokenAttributions is only supported in the app for `TextClassificationRecord` (and even more precisely only those with multi_label=False) #57
- [x] If possible I would a very brief intro to the reference (something that is maintainable) after the h1 (https://docs.rubrix.ml/en/latest/references/api_reference.html#api-reference). #73
- [x] The following sentence seems out of place "Rubrix Init Method" after Actions https://docs.rubrix.ml/en/latest/references/api_reference.html#module-rubrix #57
- [x] I would remove the docstrings from https://docs.rubrix.ml/en/latest/getting_started/concepts.html#methods and just leave the examples and a link to each reference in this section. #73 
- [x] I would align the naming: Actions (in the reference) and Methods (in the concepts section). #57
- [x] As @dcfidalgo said once I also like minimal usage examples in the docstrings which could be rendered in this reference (if it's possible without too much hassle, maybe reusing the examples we have in the concepts sections (low priority) #73

Of course any other improvement is welcome!

**Comment by dvsrepo** [comment]
Ah and I would use `Reference` instead of `References` for the main section as I think is more standard, what do you think?

**Comment by ignacioct** [comment]
> Ah and I would use `Reference` instead of `References` for the main section as I think is more standard, what do you think?

+1

> * [ ]  I don't know if we should clearly state that https://docs.rubrix.ml/en/latest/references/api_reference.html#rubrix.client.models.TokenAttributions is only supported in the app for `TextClassificationRecord` (and even more precisely only those with multi_label=False)

Isn't this for `TokenClassificationRecord`? 

> * [ ]  The following sentence seems out of place "Rubrix Init Method" after Actions https://docs.rubrix.ml/en/latest/references/api_reference.html#module-rubrix

Yes, that seems to be an ancient docstring that has survived until today.

> * [ ]  I would remove the docstrings from https://docs.rubrix.ml/en/latest/getting_started/concepts.html#methods and just leave the examples and a link to each reference in this section.

+1

> * [ ]  I would align the naming: Actions (in the reference) and Methods (in the concepts section).

For me, methods is the winner.

**Comment by dvsrepo** [comment]
Cool @ignacioct  thanks for your feedback.

Regarding this https://docs.rubrix.ml/en/latest/references/api_reference.html#rubrix.client.models.TokenAttributions this reminds me we have to include a brief guide on how to use this feature. Basically the idea is that you can use interpretability methods such as those offered by Captum.ai or Lime to log the attribution (or importance) of each token for each prediction and this will be visualized in the UI. It works only for multiclass text classification now, but the data model is designed for multilabel and potentially net as well. I have an idea of a simple outline and I guess it's better as a guide than as a tutorial. I can briefly introduce you this and we'll see if we can tackle it.

**Comment by dcfidalgo** [comment]
> As we will eventually have a REST API reference and a UI (or app) reference, I would rather call it something like Python library API or just without the API, but I am open to suggestions.

In #57 i used `Python client API` as section title, hope this is ok.

**Comment by dvsrepo** [comment]
Definitely!

**Comment by dvsrepo** [comment]
Closing this
